/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx_gpio_driver.h" // use "" to include different files
// do NOT include driver.c file, let the compiler handle the connection among different .c files

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	/*
	 * set up GPIOA properly
	 */
	GPIO_Handle_t GPIO_LED;

	GPIO_LED.pGPIOx = GPIOA;

	GPIO_LED.GPIO_PinConfig.GPIO_PinNumber = 5;
	GPIO_LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GPIO_LED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_LED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	// Alternate Function Mode is NOT applicable here since Mode != AltFn

	/*
	 * Enable Port A
	 */
	GPIO_PeriClockControl(GPIOA, ENABLE);

	GPIO_Init(&GPIO_LED); // GPIO_Init takes in a pointer parameter, use '&' to get the address of GPIO_LED


	/*
	 * set up GPIOC properly
	 */
	GPIO_Handle_t GPIO_USER_BUTTON;

	GPIO_USER_BUTTON.pGPIOx = GPIOC;

	GPIO_USER_BUTTON.GPIO_PinConfig.GPIO_PinNumber = 13;
	GPIO_USER_BUTTON.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GPIO_USER_BUTTON.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GPIO_USER_BUTTON.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	// Output types (OTYPER) is NOT applicable here since Mode != ODR
	// Alternate Function Mode is NOT applicable here since Mode != AltFn

	/*
	 * Enable Port C
	 */
	GPIO_PeriClockControl(GPIOC, ENABLE);

	GPIO_Init(&GPIO_USER_BUTTON);

	while (1){
		// Nucleo Buttons are normally Low-Active
		// if pressed, it will read low-level (0) -> 0V
		// if released, it will read high-level (1) -> 3.3V
		if (GPIO_ReadFromInputPin(GPIOC, 13) == DISABLE){
			GPIO_WriteToOutputPin(GPIOA, 5, ENABLE); // ENABLE PA5 -> light up LED2
		}else{
			GPIO_WriteToOutputPin(GPIOA, 5, DISABLE);
		}
	}
}
