/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// --- Step 1: Clock Configuration ---
	// Enable the clock for GPIO Port A.
	// Base Address of RCC: 0x4002 3800
	// Register: RCC_AHB1ENR (Offset 0x30) -> Address: 0x4002 3830
	// Bit 0 (GPIOAEN) controls the GPIOA clock. Set to 1 to enable.
	*(volatile uint32_t*)(0x40023800 + 0x30) |= (1 << 0);

	// --- Step 2: GPIO Mode Configuration ---
	// Configure PA5 (LED2) as General Purpose Output mode.
	// Base Address of GPIO: 0x4002 0000
	// Register: GPIOx_MODER (offset 0x00) -> Address: 0x4002 0000
	// PA5 corresponds to MODER5 [bits 11:10]
	// Desired pattern: 01 (General Purpose Output).

	// First, clear bits 11 and 10 to reset state (00) to avoid conflict.
	// ~(3 << 10) creates a mask where bits 11 and 10 are 0, others are 1.
	// equivalent to ~(0b11 << 10)
	*(volatile uint32_t*)(0x40020000 + 0x00) &= ~(3 << 10);

	// Then, set bit 10 to 1. Result: 01 (Output Mode).
	*(volatile uint32_t*)(0x40020000 + 0x00) |= (1 << 10);

	// --- Step 3: Output Control ---
	// Set PA5 output to High (3.3V) to turn on the LED.
	// Register: GPIOx_ODR (offset 0x14) -> Address: 0x4002 0014
	// Set Bit 5 (ODR5) to 1.
	*(volatile uint32_t*)(0x40020000 + 0x14) |= (1 << 5);

	while (1){
		// Loop forever, LD2 remains ON.
	}
}
