/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    // ====================================================================
    // Step 1: Clock Configuration (Power Up)
    // ====================================================================
    // Purpose: Before using any peripheral (GPIO), we must enable its clock.
    // Reference: RM0390 Reference Manual - Memory Map & RCC Section.

    // Base Address of RCC (Reset and Clock Control): 0x4002 3800
    // Register: RCC_AHB1ENR (AHB1 Peripheral Clock Enable Register)
    // Offset: 0x30 -> Absolute Address: 0x4002 3830

    // Logic:
    // Bit 2 controls GPIOC (for the User Button)
    // Bit 0 controls GPIOA (for the LD2 LED)
    // Writing '1' enables the clock.
    *(volatile uint32_t*)(0x40023800 + 0x30) |= (1 << 2); // Enable GPIOC
    *(volatile uint32_t*)(0x40023800 + 0x30) |= (1 << 0); // Enable GPIOA

    // ====================================================================
    // Step 2: GPIO Mode Configuration (Input vs Output)
    // ====================================================================
    // Hardware Mapping:
    // - Blue USER Button -> Connected to PC13 (Port C, Pin 13)
    // - Green LED (LD2)  -> Connected to PA5  (Port A, Pin 5)

    // Register: GPIOx_MODER (Mode Register)
    // Offset: 0x00 for both ports.

    // --- Configure PA5 (LED) as Output ---
    // Base Address of GPIOA: 0x4002 0000
    // Target: Pin 5. Controlled by bits [11:10].
    // Desired Mode: General Purpose Output (Binary: 01)

    // 1. Clear bits 11 and 10 (Reset state) to avoid conflicts.
    *(volatile uint32_t*)(0x40020000 + 0x00) &= ~(3 << 10);
    // 2. Set bit 10 to '1' to select Output Mode (01).
    *(volatile uint32_t*)(0x40020000 + 0x00) |= (1 << 10);

    // --- Configure PC13 (Button) as Input ---
    // Base Address of GPIOC: 0x4002 0800
    // Target: Pin 13. Controlled by bits [27:26].
    // Desired Mode: Input (Binary: 00)

    // 1. Clear bits 27 and 26. Since Input mode is '00', clearing them is enough.
    *(volatile uint32_t*)(0x40020800 + 0x00) &= ~(3 << 26);

    // ====================================================================
    // Step 3: Main Loop (Polling)
    // ====================================================================
    while (1){
        // Goal: Implement "Active Low" logic.
        // The schematic shows the button pulls the pin to Ground (0) when pressed.
        // Released = 1 (High/3.3V), Pressed = 0 (Low/GND).

        // Addresses:
        // - IDR (Input Data Register) Offset: 0x10. Used to READ button.
        // - ODR (Output Data Register) Offset: 0x14. Used to WRITE LED.

        // Logic Check:
        // 1. Read the 32-bit value from GPIOC_IDR.
        // 2. Shift right by 13 (>> 13) to bring the 13th bit to position 0.
        // 3. Bitwise AND with 1 (& 1) to mask/ignore all other bits.
        // 4. Check if the result is 0 (Pressed).

        if (((*(volatile uint32_t*)(0x40020800 + 0x10) >> 13) & 1) == 0){
            // Case: Button IS Pressed (Input is Low/0)
            // Action: Turn LED ON (Set PA5 to High/1)
            *(volatile uint32_t*)(0x40020000 + 0x14) |= (1 << 5);
        }
        else{
            // Case: Button IS NOT Pressed (Input is High/1 - Default State)
            // Action: Turn LED OFF (Reset PA5 to Low/0)
            *(volatile uint32_t*)(0x40020000 + 0x14) &= ~(1 << 5);
        }
    }
}
